spring:
  main:
    banner-mode: off

metrics.graphite:
  enabled: false
  host: #
  port: 3000
  prefix: 'gatekeeper-sparrow'
  interval: 30
  intervalSeconds: SECONDS

vertx.http-server:
  port: 8080
  maxHeaderSize: 16384
  idleTimeout: 10
  ssl: false

spring.cache:
  type: jcache
  jcache.provider: org.ehcache.jsr107.EhcacheCachingProvider

cache.ad-requests-cache:
  durationAmount: 10
  durationTimeUnit: SECONDS
